# Generated by Django 5.1 on 2024-08-18 21:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sleep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slept_at", models.DateTimeField()),
                (
                    "sleep_length",
                    models.FloatField(
                        validators=[django.core.validators.MinLengthValidator(0)]
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.profile"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
