# Generated by Django 5.1 on 2024-08-18 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sleep", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleep",
            name="sleep_length",
            field=models.FloatField(
                max_length=2, validators=[django.core.validators.MinLengthValidator(0)]
            ),
        ),
    ]
