# Generated by Django 5.1 on 2024-08-25 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sleep", "0002_alter_sleep_sleep_length"),
        ("user", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleep",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.profile"
            ),
        ),
        migrations.AlterField(
            model_name="sleep",
            name="sleep_length",
            field=models.FloatField(
                max_length=2, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
