# Generated by Django 5.1 on 2024-08-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sleep", "0003_alter_sleep_profile_alter_sleep_sleep_length"),
        ("user", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleep",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sleeps",
                to="user.profile",
            ),
        ),
    ]
